
project_id = "xwaxvupymmlbehlocyzt"

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-bulk-email-reminders]
verify_jwt = false

[functions.send-email-reminder]
verify_jwt = false

[functions.get-pagarme-balance]
verify_jwt = false

[functions.create-patient-invite]
verify_jwt = true

[functions.validate-patient-invite]
verify_jwt = false

[functions.submit-patient-form]
verify_jwt = false

[functions.send-support-ticket]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.check-stripe-subscription]
verify_jwt = true

[functions.stripe-customer-portal]
verify_jwt = true

[functions.cleanup-duplicate-subscriptions]
verify_jwt = true

[functions.cleanup-subscriptions]
verify_jwt = false

[functions.send-appointment-reminder]
verify_jwt = true

[functions.send-automatic-appointment-reminders]
verify_jwt = false

[functions.get-reminder-system-metrics]
verify_jwt = true
