
project_id = "xwaxvupymmlbehlocyzt"

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-bulk-email-reminders]
verify_jwt = false

[functions.send-email-reminder]
verify_jwt = false
